### PR TITLE
Adding a broken test to try and break it.

### PR DESCRIPTION
**Pull request by smeepz**

### CODE REVIEW

**Review by Kaikka — APPROVED** [review]
Very bad test this will crash!!

**Comment by Kaikka** [comment]
Sorry your tests fail, u noob

**Comment by smeepz** [comment]
Whoops! Caught me slipping!

**Review by Kaikka — CHANGES_REQUESTED** [review]
code breaks. pls fixx

**Comment by smeepz** [comment]
I will have to fix this, before I push it again!

**Pull request closed without merging**
